### ISSUE TITLE
Hsluv not recognized as Constructor in Vue (Nuxt)

### ISSUE THREAD

**Issue by surfinzap** [hsluv/hsluv-javascript#1]
I've tried to use Hsluv library in [Nuxt project](https://nuxtjs.org/docs/get-started/installation) (2.15.8) that uses Vue (2.6.14). Following your documentation, I imported the library in the component:

```
<script>
import { Hsluv } from 'hsluv';

export default {
  props : {
    bgColor: {
      type: String,
      default: '#ddd'
    },
    ...
  },

  computed: {
    bgColor: {
      get() {
        var conv = new Hsluv();
        conv.hsluv_h = 10;
        conv.hsluv_s = 80;
        conv.hsluv_l = this.hsluvL;
        conv.hsluvToHex();
        return conv.hex;
      }
    }
  }
}
</script>
```

which results in following error:
![image](https://user-images.githubusercontent.com/1387798/191472211-5bb662fd-0ec7-434f-a689-15266d00f613.png)

I hadn't had any luck troubleshooting this via vue/nuxt docs, so I'm curious if there is any issue with the package itself?

**Comment by boronine** [comment]
I see what the confusion is... The GitHub's master branch is documenting a pre-release version v1.0.0-rc3, but with npm you installed an older 0.1.0 version. Actually, after reading your message I pulled the trigger on the v1.0.0 release, so if you upgrade your package the code should work.

Thanks for the report! Feel free to reopen if you have any more issues.

**Comment by surfinzap** [comment]
Thanks for looking into it! I've updated the package, however, now I'm getting different error in the terminal:
```
This dependency was not found:                                                                                                               friendly-errors 12:45:32  
                                                                                                                                             friendly-errors 12:45:32  
* hsluv in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/color-chip.vue?vue&type=script&lang=js&
```

**Comment by boronine** [comment]
There's infinite ways that webpack can be configured, so I can't do much here... You could try using ESM imports with the full filename specified: dist/esm/hsluv.js, or try CommonJS version (`require`). Failing that I would need to see your configuration, ideally a self-contained repo that reproduces this issue.

**Comment by surfinzap** [comment]
Thanks for your suggestions. I've tried the fullname and ``require`` option, but unfortunately it did not work. When I hover over the import, this is the path where my repo expects the file:
![image](https://user-images.githubusercontent.com/1387798/191503773-9016b652-0cfe-43bc-9e28-cf66224f06d2.png)

I guess the file for the ``import`` is located in path ``./node_modules/hsluv/dist/esm/hsluv.js`` so I'm not sure why my repo expects it in a different location. 

If you'd like to take a look at the repo itself, I could give you access or send a repo.

**Comment by boronine** [comment]
The new package uses a special technique to ship both ESM and CJS versions, maybe it's causing the failure. If you could give me access to your repo I would happily debug... Need to make sure others are not affected as well.

**Comment by surfinzap** [comment]
Thanks for looking into it; I've sent you the access. The file where I import the library is ``color-chip.vue``. 

Earlier today, I've noticed that you're using [exports](https://nodejs.org/api/packages.html#packages_exports) in your package a checked the compatibility with my node/npm, which should be ok. However, what min versions of node/npm would you recommend?

**Comment by boronine** [comment]
I was able to compile your code, I just had to upgrade Sass:

```
-    "node-sass": "^5.0.0",
+    "node-sass": "^7.0.3",
```

I was able to get the build work with both CJS:

```javascript
const {Hsluv} = require('hsluv/dist/cjs/hsluv');
```

And ESM:

```javascript
import { Hsluv } from 'hsluv/dist/esm/hsluv.js';
```

You should be able to use either. I wanted to debug the webpack issue but I literally followed "webpack cli init" to get a test environment and it's broken out of the box. Webpack is a clusterfuck as always, I'm not going to debug it.

**Comment by surfinzap** [comment]
Thanks for getting to the root case! 🙏With an updated node-sass and a direct path it works at my end as well.
