### ISSUE TITLE
GitHub 1.0.0 release?

### ISSUE THREAD

**Issue by JoshuaGrams** [hsluv/hsluv-javascript#2]
Are you going to make a GitHub release of 1.0.0? I clicked on "the latest hsluv.min.js" link in the README and downloaded it, not noticing that it was still the old release with the old API, and was confused when it didn't work. I cloned the repository and built it myself, but it would have been nice to just download the built file...

**Comment by boronine** [comment]
Looks like I forgot to publish the draft, thanks for bringing it to my attention!

New release: https://github.com/hsluv/hsluv-javascript/releases/tag/v1.0.0
