### ISSUE TITLE
Converting hex to rgb assumes a 6-digit hex

### ISSUE THREAD

**Issue by ilikescience** [hsluv/hsluv-javascript#7]
The method `.hexToHsluv()` assumes that the hex provided is 6 digits, eg `#ff0000`. However, hex colors can be 3 digits, where each digit is replicated to get the 6-digit value; eg `#f00` becomes `#ff0000`.[^1] 

A simple fix would be to check if the hex provided is 3 digits and converting if so.

[^1]: https://www.w3.org/TR/css-color-3/#numerical

**Comment by boronine** [comment]
I'd rather not support this, it's not useful enough to warrant extra code
